import{a as p,S as g,i as l}from"./assets/vendor-CZCqCKWq.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const y="49627345-81d87c81626646e8cd4c1e6ab",h=i=>p("https://pixabay.com/api/",{params:{key:y,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:"30"}}),m=document.querySelector(".gallery"),d=document.querySelector(".loader"),L=new g(".gallery-card a",{captionsData:"alt",captionDelay:"250"});function b(i){m.innerHTML=i.map(({webformatURL:r,largeImageURL:o,tags:s,likes:e,views:t,comments:a,downloads:f})=>`<li class="image-item">
            <div class="gallery-card"><a href="${o}"><img src="${r}" alt="${s}" class="image"/></a></div>
            <ul class="image-info">
                <li>Likes<p>${e}</p></li>
                <li>Views<p>${t}</p></li>
                <li>Comments<p>${a}</p></li>
                <li>Downloads<p>${f}</p></li>
            </ul>
        </li>`).join(""),L.refresh()}const v=()=>{m.innerHTML=""},S=()=>{d.classList.remove("visually-hidden")},c=()=>{d.classList.add("visually-hidden")},n=document.querySelector(".form");n.addEventListener("submit",w);function w(i){i.preventDefault(),S(),v();const r=n.elements[0].value.toLowerCase().trim();if(!(r.length>0)){l.show(u),c(),n.reset();return}h(r).then(o=>{const s=o.data.hits;if(!s.length){l.show(u);return}b(s)}).catch(o=>console.log(o)).finally(()=>{c(),n.reset()})}const u={message:"Sorry, there are no images matching your search query. Please try again!",theme:"light",iconColor:"#fafafb",color:"#ef4040",messageColor:"#fafafb",position:"topRight",messageSize:"16px",messageSize:"150%",iconUrl:"./img/bi_x-octagon.png"};
//# sourceMappingURL=index.js.map
