import{a as m,S as d,i as f}from"./assets/vendor-CZCqCKWq.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const p="49627345-81d87c81626646e8cd4c1e6ab",g=i=>m("https://pixabay.com/api/",{params:{key:p,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:"30"}}),l=document.querySelector(".gallery"),c=document.querySelector(".loader"),y=new d(".gallery-card a",{captionsData:"alt",captionDelay:"250"});function h(i){l.innerHTML=i.map(({webformatURL:r,largeImageURL:o,tags:s,likes:e,views:t,comments:a,downloads:u})=>`<li class="image-item">
            <div class="gallery-card"><a href="${o}"><img src="${r}" alt="${s}" class="image"/></a></div>
            <ul class="image-info">
                <li>Likes<p>${e}</p></li>
                <li>Views<p>${t}</p></li>
                <li>Comments<p>${a}</p></li>
                <li>Downloads<p>${u}</p></li>
            </ul>
        </li>`).join(""),y.refresh()}const L=()=>{l.innerHTML=""},b=()=>{c.classList.remove("visually-hidden")},v=()=>{c.classList.add("visually-hidden")},n=document.querySelector(".form");n.addEventListener("submit",S);function S(i){i.preventDefault(),b(),L();const r=n.elements[0].value.toLowerCase().trim();g(r).then(o=>{const s=o.data.hits;if(!s.length){f.show(q);return}h(s)}).catch(o=>console.log(o)).finally(()=>{v(),n.reset()})}const q={message:"Sorry, there are no images matching your search query. Please try again!",theme:"light",iconColor:"#fafafb",color:"#ef4040",messageColor:"#fafafb",position:"topRight",messageSize:"16px",messageSize:"150%",iconUrl:"./img/bi_x-octagon.png"};
//# sourceMappingURL=index.js.map
